[phases.setup]
nixPkgs = ["python39", "python39Packages.pip"]

[phases.install]
cmds = ["pip install --break-system-packages -r requirements.txt"]

[phases.build]
cmds = ["python3 manage.py collectstatic --noinput"]

[start]
cmd = "gunicorn emp54_django.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
