[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "gcc", "stdenv.cc.cc.lib"]
nixLibs = ["stdenv.cc.cc.lib"]

[phases.install]
cmds = ["pip install --break-system-packages -r requirements.txt"]

[phases.build]
cmds = ["python3 manage.py collectstatic --noinput"]

[start]
cmd = "python3 -m gunicorn emp54_django.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
